version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travellight-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/travellight
      - SPRING_DATASOURCE_USERNAME=travellight
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - travellight-network

  db:
    image: postgres:15
    container_name: travellight-db
    environment:
      - POSTGRES_DB=travellight
      - POSTGRES_USER=travellight
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travellight -d travellight"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - travellight-network

volumes:
  postgres_data:

networks:
  travellight-network:
    driver: bridge