version: '3.8'

services:
  db:
    image: postgres:15
    container_name: travellight-dev-db
    environment:
      - POSTGRES_DB=travellight
      - POSTGRES_USER=travellight
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travellight -d travellight"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_dev_data: