spring:
  application:
    name: TravelLight

  # RDS 데이터베이스 설정 (환경변수로 오버라이드됨)
  datasource:
    url: jdbc:postgresql://travel-light.czgyiuy6s6zy.ap-northeast-2.rds.amazonaws.com:5432/travellight
    username: postgres
    password: TravelLight4-1
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 이메일 설정
  mail:
    enabled: true
    host: smtp.gmail.com
    port: 587
    username: haveagoodtrip.travellight@gmail.com
    password: cnyg lbpx ruvw tskl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # 날짜/시간 설정
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Seoul

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 메시지 설정
  messages:
    basename: messages
    encoding: UTF-8

  # Redis 캐싱 설정
  data:
    redis:
      url: redis://${REDIS_HOST:redis}:${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 서버 포트 설정
server:
  port: 8080

# 로깅 설정 (운영환경용 - DEBUG 제거)
logging:
  level:
    org.springframework.security: INFO
    org.example.travellight: INFO
    org.springframework.web: INFO

# Naver Maps API
naver:
  maps:
    client:
      id: r23gqqq271
      secret: nCrtgfs2DRdDzKV3bqYDM8djDxPIEJEUyZ6Hv7b4

# Google Gemini API 설정
gemini:
  model:
    name: ${GEMINI_MODEL_NAME:gemini-2.0-flash-exp}